use generic_packet_derive::GenericPacket;
use packet_serde_derive::PacketSerde;

use crate::minecraft::{
    packet::{GenericPacket, PacketReadable, PacketSerde, PacketWritable},
    types,
};

// ###### Generic Clientbound Login Packet ######

#[derive(PacketSerde, GenericPacket, Debug, Clone)]
pub enum ClientboundLoginPacket {
    Disconnect {
        reason: types::String,
    },
    EncryptionRequest {
        server_id: types::String,            // max 20 characters
        public_key: types::ByteArray,        // the server's public key in bytes
        verify_token: types::ByteArray,      // A sequence of random bytes generated by the server.
        should_authenticate: types::Boolean, // Whether the client should attempt to authenticate through mojang servers.
    },
    LoginSuccess {
        uuid: types::UUID,
        username: types::String,
        properties: types::Array<types::SingedProperty>,
    },
    SetCompression {
        threshold: types::VarInt,
    },
    PluginRequest {
        message_id: types::VarInt,
        channel: types::Identifier,
        data: types::UnsizedByteArray,
    },
    CookieRequest {
        key: types::Identifier,
    },
}